### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ziasistani** [HajdiBengu/Hashlock#1]
### Dear HajdiBengu
First and foremost,  I want to thank you for sharing your improved hashlock code.
FYI, I use smartpy-cli for compiling my codes.

I tried to compile hashlock.py with below command
`SmartPy.sh compile hashlock.py ./release`
and I got below error 
`[error] Target "compilation" not found in ./release/scenario.json`

then 

I added below line to the code 
`sp.add_compilation_target("release", Hashlock( sp.address("tz1TQnU87CQMz7wQEMT4i7sWQgsqyyff7Eps") ) )` 
and I recompile with the same way and I've got below error:
`[error] File "smartML/michelson_base/typing.ml", line 206, characters 27-33: Assertion failed`

How can I compile hashlock.py by ?

**Comment by HajdiBengu** [comment]
Thanks Yaser. I'm not sure about the cli compiler, but you can use the SmartPy online IDE. It compiles the code automatically to Michelson.

**Comment by ziasistani** [comment]
Yes, Thanks.
I tested it successfully in online IDE but I was not successful in CLI.
